### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by xfoldvar** [michalvalkoun/noyce_joyce_nixie#47]
Hi, is this project still alive? Im waiting for iOS release, do you plan to release it? I have an nixie clock and i need some way to sync time because time is getting out of sync very often. Is there any bt api description which you will be able to share?

**Comment by michalvalkoun** [comment]
Yes, the project is still alive. I have been working on it in my free time. I'm happy to inform you that the IOS version is now available, and you can access it at this [link](https://apps.apple.com/us/app/noyce-joyce-nixie/id1672340229)
